# Generated by Django 4.1 on 2022-09-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bjjmoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=64)),
                ('move_des', models.CharField(max_length=500)),
                ('thoughts', models.CharField(max_length=500)),
            ],
        ),
    ]
