# Generated by Django 4.1 on 2022-09-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0002_bjjmoves'),
    ]

    operations = [
        migrations.CreateModel(
            name='classtracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.CharField(max_length=64)),
                ('number_of_rolls', models.IntegerField()),
            ],
        ),
    ]
