# Generated by Django 4.1 on 2022-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0003_classtracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moves',
            name='position',
        ),
        migrations.AddField(
            model_name='moves',
            name='position_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
