# Generated by Django 4.1 on 2022-10-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0004_remove_moves_position_moves_position_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=64)),
            ],
        ),
    ]
