# Generated by Django 4.1 on 2022-10-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0005_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testvar', models.CharField(max_length=64)),
            ],
        ),
    ]
