# Generated by Django 4.1 on 2022-10-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0006_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testtable',
        ),
    ]
