# Generated by Django 4.1 on 2022-10-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0008_testtbs1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testtbs1006',
        ),
    ]
