# Generated by Django 4.1 on 2022-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0009_delete_testtbs1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='is_offence',
            field=models.BooleanField(default=True),
        ),
    ]
