# Generated by Django 4.1 on 2022-12-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0010_moves_is_offence'),
    ]

    operations = [
        migrations.CreateModel(
            name='testfk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='calltestfk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=64)),
                ('dob', models.CharField(max_length=64)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiujitsu_moves.testfk')),
            ],
        ),
    ]
