# Generated by Django 4.1 on 2022-12-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiujitsu_moves', '0012_remove_moves_position_id_moves_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calltestfk',
        ),
        migrations.DeleteModel(
            name='testfk',
        ),
    ]
